// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaEgpflIg8kaLtPp1U_mDMDVWZAiECTSk',
    appId: '1:880017488073:web:53fd622ea188eb186b7518',
    messagingSenderId: '880017488073',
    projectId: 'elderly-health-app',
    authDomain: 'elderly-health-app.firebaseapp.com',
    storageBucket: 'elderly-health-app.appspot.com',
    measurementId: 'G-S2W5HLTHN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHsfRbMiYh9bvnZP8RQW3NsJGQKKJ240w',
    appId: '1:880017488073:android:bbb784289bed53b96b7518',
    messagingSenderId: '880017488073',
    projectId: 'elderly-health-app',
    storageBucket: 'elderly-health-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZeGFCnNPhbMH7OrBBFnlVbbRhWOACgDg',
    appId: '1:880017488073:ios:3db16efd9c5a577e6b7518',
    messagingSenderId: '880017488073',
    projectId: 'elderly-health-app',
    storageBucket: 'elderly-health-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
